- name: Variable Playbook
  hosts: all
  vars:
   URL: "global.cloudblitz.in"
  vars: 
  tasks:
      - name: print my url1
        debug:
          msg: "{{ URL }}"

      - name: print my url2
        debug:
          msg: "{{ URL }}" 
        vars:
          URL: "local.cloudblitz.com"

      - name: print my url3
        debug:
          msg: "{{ URL }}"


