- name: Variable Playbook
  hosts: all
  vars:
   URL: "google.com"
  tasks:
      - name: print my url1
        debug:
          msg: "{{ URL }}"
      - name: print my url2
        debug:
          msg: "{{ URL }}" 
        vars:
            
      - name: print my url3
        debug:
          msg: "{{ URL }}"


