- name: Variable Playbook
  hosts: all
  vars:
   URL: "google.com"
  tasks:
      - name: print my url
        debug:
          msg: "{{ URL }}"
         name: print my url
        debug:
          msg: "{{ URL }}"  

           name: print my url
        debug:
          msg: "{{ URL }}"